// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ignore

// generate_types.go generates type definitions from runtime source files.
//
// This tool parses struct definitions from Go runtime and internal/abi packages
// and generates corresponding type definitions in moduledata_types.go. This
// avoids duplicating complex type definitions and ensures consistency between
// objfile's understanding of runtime data structures and the actual runtime.
//
// Usage:
//   go run generate_types.go
//
// The generated file should NOT be edited manually - rerun this tool instead.
//
// Types are sourced from:
//   - src/runtime/*.go (moduledata, pcHeader, etc.)
//   - src/internal/abi/*.go (Type system types)
//
// The generator handles:
//   - Embedded struct types (no field name)
//   - sys.NotInHeap marker (output as comment)
//   - struct{} anonymous fields
//   - Field comments from original sources

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const (
	goroot     = "../../.."
	outputFile = "moduledata_types.go"
)

var targetTypes = []struct {
	name string
	src  string
}{
	{"pcHeader", "runtime/symtab.go"},
	{"modulehash", "runtime/symtab.go"},
	{"functab", "runtime/symtab.go"},
	{"textsect", "runtime/symtab.go"},
	{"findfuncbucket", "runtime/symtab.go"},
	{"stackmap", "runtime/symtab.go"},
	{"Func", "runtime/symtab.go"},
	{"moduledata", "runtime/symtab.go"},
	{"inlinedCall", "runtime/symtabinl.go"},
	{"initTask", "runtime/proc.go"},
	{"ptabEntry", "runtime/plugin.go"},
	{"bitvector", "runtime/stack.go"},
	{"stringStruct", "runtime/string.go"},
	{"stackObjectRecord", "runtime/stack.go"},
	{"_func", "runtime/runtime2.go"},
	{"itab", "runtime/runtime2.go"},
	{"UncommonType", "internal/abi/type.go"},
	{"Imethod", "internal/abi/type.go"},
	{"Method", "internal/abi/type.go"},
	{"InterfaceType", "internal/abi/type.go"},
	{"StructType", "internal/abi/type.go"},
	{"StructField", "internal/abi/type.go"},
	{"ArrayType", "internal/abi/type.go"},
	{"SliceType", "internal/abi/type.go"},
	{"ChanType", "internal/abi/type.go"},
	{"PtrType", "internal/abi/type.go"},
	{"FuncType", "internal/abi/type.go"},
	{"ITab", "internal/abi/iface.go"},
	{"EmptyInterface", "internal/abi/iface.go"},
}

func main() {
	var genDecl bytes.Buffer

	for _, t := range targetTypes {
		typeName := t.name
		srcFile := t.src
		inputFile := filepath.Join(goroot, srcFile)
		fset := token.NewFileSet()
		node, err := parser.ParseFile(fset, inputFile, nil, parser.ParseComments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to parse %s: %v\n", inputFile, err)
			os.Exit(1)
		}

		for _, decl := range node.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Name.Name != typeName {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				fmt.Fprintf(&genDecl, "// Copy of structure from %s\n", srcFile)
				fmt.Fprintf(&genDecl, "type %s struct {\n", typeName)
				for _, field := range st.Fields.List {
					fieldType := typeString(field.Type)

					if fieldType == "sys.NotInHeap" {
						fmt.Fprintf(&genDecl, "\t// sys.NotInHeap // Only in static data\n")
						continue
					}

					if field.Comment != nil && len(field.Names) == 0 {
						fmt.Fprintf(&genDecl, "\t// %s\n", strings.TrimSpace(field.Comment.Text()))
					}

					names := make([]string, len(field.Names))
					for i, n := range field.Names {
						names[i] = n.Name
					}

					if len(names) > 1 {
						fmt.Fprintf(&genDecl, "\t%s %s\n", strings.Join(names, ", "), fieldType)
					} else if len(names) == 1 {
						fmt.Fprintf(&genDecl, "\t%s %s", names[0], fieldType)
						if field.Comment != nil {
							fmt.Fprintf(&genDecl, " // %s", strings.TrimSpace(field.Comment.Text()))
						}
						fmt.Fprintln(&genDecl)
					} else {
						fmt.Fprintf(&genDecl, "\t%s\n", fieldType)
					}
				}
				fmt.Fprintln(&genDecl, "}")
				fmt.Fprintln(&genDecl)
			}
		}
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by generate_types.go; DO NOT EDIT.")
	fmt.Fprintln(&buf, "//go:generate go run generate_types.go")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package objfile")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "import (")
	fmt.Fprintln(&buf, "\t\"internal/abi\"")
	fmt.Fprintln(&buf, "\t\"unsafe\"")
	fmt.Fprintln(&buf, ")")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "// Type aliases for types used in generated struct definitions")
	fmt.Fprintln(&buf, "type Type = abi.Type")
	fmt.Fprintln(&buf, "type _type = abi.Type") // backward compatibility alias
	fmt.Fprintln(&buf, "type Name = abi.Name")
	fmt.Fprintln(&buf, "type Kind = abi.Kind")
	fmt.Fprintln(&buf, "type TFlag = abi.TFlag")
	fmt.Fprintln(&buf, "type ChanDir = abi.ChanDir")
	fmt.Fprintln(&buf, "type NameOff = abi.NameOff")
	fmt.Fprintln(&buf, "type TypeOff = abi.TypeOff")
	fmt.Fprintln(&buf, "type TextOff = abi.TextOff")
	fmt.Fprintln(&buf, "type typeOff = abi.TypeOff") // lowercase alias for ptabEntry
	fmt.Fprintln(&buf, "type nameOff = abi.NameOff") // lowercase alias for ptabEntry
	fmt.Fprintln(&buf, "type name = abi.Name")       // lowercase alias for name() method return
	fmt.Fprintln(&buf, "type itab struct {")
	fmt.Fprintln(&buf, "\tInter *InterfaceType")
	fmt.Fprintln(&buf, "\tType  *Type")
	fmt.Fprintln(&buf, "\tHash  uint32")
	fmt.Fprintln(&buf, "\t_     uint32 // padding")
	fmt.Fprintln(&buf, "\tFun   [1]uintptr")
	fmt.Fprintln(&buf, "}")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "// Types copied from runtime source files")
	fmt.Fprintln(&buf)
	buf.WriteString(genDecl.String())

	if err := os.WriteFile(outputFile, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputFile)
}

func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StructType:
		if t.Fields == nil || len(t.Fields.List) == 0 {
			return "struct{}"
		}
		var buf bytes.Buffer
		buf.WriteString("struct{")
		for i, f := range t.Fields.List {
			if i > 0 {
				buf.WriteString("; ")
			}
			for j, n := range f.Names {
				if j > 0 {
					buf.WriteString(", ")
				}
				buf.WriteString(n.Name)
			}
			buf.WriteString(" ")
			buf.WriteString(typeString(f.Type))
		}
		buf.WriteString("}")
		return buf.String()
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt)
		}
		return "[" + typeString(t.Len) + "]" + typeString(t.Elt)
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.MapType:
		return "map[" + typeString(t.Key) + "]" + typeString(t.Value)
	case *ast.BasicLit:
		return t.Value
	case *ast.FuncType:
		var buf bytes.Buffer
		buf.WriteString("func(")
		if t.Params != nil {
			for i, p := range t.Params.List {
				if i > 0 {
					buf.WriteString(", ")
				}
				if len(p.Names) > 0 {
					for j, n := range p.Names {
						if j > 0 {
							buf.WriteString(", ")
						}
						buf.WriteString(n.Name)
					}
					buf.WriteString(" ")
				}
				buf.WriteString(typeString(p.Type))
			}
		}
		buf.WriteString(")")
		if t.Results != nil && len(t.Results.List) > 0 {
			buf.WriteString(" ")
			if len(t.Results.List) == 1 && len(t.Results.List[0].Names) == 0 {
				buf.WriteString(typeString(t.Results.List[0].Type))
			} else {
				buf.WriteString("(")
				for i, r := range t.Results.List {
					if i > 0 {
						buf.WriteString(", ")
					}
					if len(r.Names) > 0 {
						for j, n := range r.Names {
							if j > 0 {
								buf.WriteString(", ")
							}
							buf.WriteString(n.Name)
						}
						buf.WriteString(" ")
					}
					buf.WriteString(typeString(r.Type))
				}
				buf.WriteString(")")
			}
		}
		return buf.String()
	default:
		return "interface{}"
	}
}

