// Code generated by generate_types.go; DO NOT EDIT.
//go:generate go run generate_types.go

package objfile

import (
	"internal/abi"
	"unsafe"
)

// Type aliases for types used in generated struct definitions
type Type = abi.Type
type _type = abi.Type
type Name = abi.Name
type Kind = abi.Kind
type TFlag = abi.TFlag
type ChanDir = abi.ChanDir
type NameOff = abi.NameOff
type TypeOff = abi.TypeOff
type TextOff = abi.TextOff
type typeOff = abi.TypeOff
type nameOff = abi.NameOff
type name = abi.Name
type itab struct {
	Inter *InterfaceType
	Type  *Type
	Hash  uint32
	_     uint32 // padding
	Fun   [1]uintptr
}

// Types copied from runtime source files

// Copy of structure from runtime/symtab.go
type pcHeader struct {
	magic          uint32 // 0xFFFFFFF1
	pad1, pad2     uint8
	minLC          uint8   // min instruction size
	ptrSize        uint8   // size of a ptr in bytes
	nfunc          int     // number of functions in the module
	nfiles         uint    // number of entries in the file tab
	textStart      uintptr // base for function entry PC offsets in this module, equal to moduledata.text
	funcnameOffset uintptr // offset to the funcnametab variable from pcHeader
	cuOffset       uintptr // offset to the cutab variable from pcHeader
	filetabOffset  uintptr // offset to the filetab variable from pcHeader
	pctabOffset    uintptr // offset to the pctab variable from pcHeader
	pclnOffset     uintptr // offset to the pclntab variable from pcHeader
}

// Copy of structure from runtime/symtab.go
type modulehash struct {
	modulename   string
	linktimehash string
	runtimehash  *string
}

// Copy of structure from runtime/symtab.go
type functab struct {
	entryoff uint32 // relative to runtime.text
	funcoff  uint32
}

// Copy of structure from runtime/symtab.go
type textsect struct {
	vaddr    uintptr // prelinked section vaddr
	end      uintptr // vaddr + section length
	baseaddr uintptr // relocated section address
}

// Copy of structure from runtime/symtab.go
type findfuncbucket struct {
	idx        uint32
	subbuckets [16]byte
}

// Copy of structure from runtime/symtab.go
type stackmap struct {
	n        int32   // number of bitmaps
	nbit     int32   // number of bits in each bitmap
	bytedata [1]byte // bitmaps, each starting on a byte boundary
}

// Copy of structure from runtime/symtab.go
type Func struct {
	opaque struct{} // unexported field to disallow conversions
}

// Copy of structure from runtime/symtab.go
type moduledata struct {
	// sys.NotInHeap // Only in static data
	pcHeader              *pcHeader
	funcnametab           []byte
	cutab                 []uint32
	filetab               []byte
	pctab                 []byte
	pclntable             []byte
	ftab                  []functab
	findfunctab           uintptr
	minpc, maxpc          uintptr
	text, etext           uintptr
	noptrdata, enoptrdata uintptr
	data, edata           uintptr
	bss, ebss             uintptr
	noptrbss, enoptrbss   uintptr
	covctrs, ecovctrs     uintptr
	end, gcdata, gcbss    uintptr
	types, etypes         uintptr
	rodata                uintptr
	gofunc                uintptr // go.func.*
	textsectmap           []textsect
	typelinks             []int32 // offsets from types
	itablinks             []*itab
	ptab                  []ptabEntry
	pluginpath            string
	pkghashes             []modulehash
	inittasks             []*initTask
	modulename            string
	modulehashes          []modulehash
	hasmain               uint8 // 1 if module contains the main function, 0 otherwise
	bad                   bool  // module failed to load and should be ignored
	gcdatamask, gcbssmask bitvector
	typemap               map[typeOff]*_type // offset to *_rtype in previous module
	next                  *moduledata
}

// Copy of structure from runtime/symtabinl.go
type inlinedCall struct {
	funcID    abi.FuncID // type of the called function
	_         [3]byte
	nameOff   int32 // offset into pclntab for name of called function
	parentPc  int32 // position of an instruction whose source position is the call site (offset from entry)
	startLine int32 // line number of start of function (func keyword/TEXT directive)
}

// Copy of structure from runtime/proc.go
type initTask struct {
	state uint32 // 0 = uninitialized, 1 = in progress, 2 = done
	nfns  uint32
}

// Copy of structure from runtime/plugin.go
type ptabEntry struct {
	name nameOff
	typ  typeOff
}

// Copy of structure from runtime/stack.go
type bitvector struct {
	n        int32 // # of bits
	bytedata *uint8
}

// Copy of structure from runtime/string.go
type stringStruct struct {
	str unsafe.Pointer
	len int
}

// Copy of structure from runtime/stack.go
type stackObjectRecord struct {
	off       int32
	size      int32
	ptrBytes  int32
	gcdataoff uint32 // offset to gcdata from moduledata.rodata
}

// Copy of structure from runtime/runtime2.go
type _func struct {
	// sys.NotInHeap // Only in static data
	entryOff    uint32 // start pc, as offset from moduledata.text/pcHeader.textStart
	nameOff     int32  // function name, as index into moduledata.funcnametab.
	args        int32  // in/out args size
	deferreturn uint32 // offset of start of a deferreturn call instruction from entry, if any.
	pcsp        uint32
	pcfile      uint32
	pcln        uint32
	npcdata     uint32
	cuOffset    uint32     // runtime.cutab offset of this function's CU
	startLine   int32      // line number of start of function (func keyword/TEXT directive)
	funcID      abi.FuncID // set for certain special runtime functions
	flag        abi.FuncFlag
	_           [1]byte // pad
	nfuncdata   uint8   // must be last, must end on a uint32-aligned boundary
}

// Copy of structure from internal/abi/type.go
type UncommonType struct {
	PkgPath NameOff // import path; empty for built-in types like int, string
	Mcount  uint16  // number of methods
	Xcount  uint16  // number of exported methods
	Moff    uint32  // offset from this uncommontype to [mcount]Method
	_       uint32  // unused
}

// Copy of structure from internal/abi/type.go
type Imethod struct {
	Name NameOff // name of method
	Typ  TypeOff // .(*FuncType) underneath
}

// Copy of structure from internal/abi/type.go
type Method struct {
	Name NameOff // name of method
	Mtyp TypeOff // method type (without receiver)
	Ifn  TextOff // fn used in interface call (one-word receiver)
	Tfn  TextOff // fn used for normal method call
}

// Copy of structure from internal/abi/type.go
type InterfaceType struct {
	Type
	PkgPath Name      // import path
	Methods []Imethod // sorted by hash
}

// Copy of structure from internal/abi/type.go
type StructType struct {
	Type
	PkgPath Name
	Fields  []StructField
}

// Copy of structure from internal/abi/type.go
type StructField struct {
	Name   Name    // name is always non-empty
	Typ    *Type   // type of field
	Offset uintptr // byte offset of field
}

// Copy of structure from internal/abi/type.go
type ArrayType struct {
	Type
	Elem  *Type // array element type
	Slice *Type // slice type
	Len   uintptr
}

// Copy of structure from internal/abi/type.go
type SliceType struct {
	Type
	Elem *Type // slice element type
}

// Copy of structure from internal/abi/type.go
type ChanType struct {
	Type
	Elem *Type
	Dir  ChanDir
}

// Copy of structure from internal/abi/type.go
type PtrType struct {
	Type
	Elem *Type // pointer element (pointed at) type
}

// Copy of structure from internal/abi/type.go
type FuncType struct {
	Type
	InCount  uint16
	OutCount uint16 // top bit is set if last input parameter is ...
}

// Copy of structure from internal/abi/iface.go
type ITab struct {
	Inter *InterfaceType
	Type  *Type
	Hash  uint32     // copy of Type.Hash. Used for type switches.
	Fun   [1]uintptr // variable sized. fun[0]==0 means Type does not implement Inter.
}

// Copy of structure from internal/abi/iface.go
type EmptyInterface struct {
	Type *Type
	Data unsafe.Pointer
}
